# Generated by Django 6.0.5 on 2026-05-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('CORPORATE_TRAVEL', 'Corporate Travel')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(blank=True, help_text='Original source file preserved for audit purposes', null=True, upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PROCESSING', max_length=15)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'acme-corp'", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('CORPORATE_TRAVEL', 'Corporate Travel')], help_text='Denormalized from IngestionLog for efficient filtering without JOINs', max_length=30)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct'), (2, 'Scope 2 — Purchased Energy'), (3, 'Scope 3 — Value Chain')])),
                ('description', models.TextField(blank=True, help_text="Human-readable label, e.g. 'Business flight JFK→LHR'")),
                ('source_reference', models.CharField(blank=True, help_text='Original system identifier: SAP doc number, meter ID, or trip ID', max_length=255)),
                ('raw_source_data', models.JSONField(help_text='Original CSV row as received, never modified')),
                ('normalized_data', models.JSONField(default=dict, help_text='Cleaned, unit-converted intermediate form showing the transformation applied')),
                ('activity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('activity_unit', models.CharField(blank=True, max_length=50)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, help_text='MTCO2e per unit of activity', max_digits=10, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=100)),
                ('co2e_mt', models.DecimalField(blank=True, decimal_places=6, help_text='Final calculated result in Metric Tons CO2 Equivalent', max_digits=12, null=True)),
                ('period_start', models.DateField(blank=True, help_text='Billing period start for utility rows', null=True)),
                ('period_end', models.DateField(blank=True, help_text='Billing period end for utility rows', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('flag_reason', models.TextField(blank=True, help_text='Auto-populated explanation when status is FLAGGED', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='Set when status transitions to APPROVED or REJECTED. Row is immutable after this.', null=True)),
                ('ingestion_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_rows', to='ingestion.ingestionlog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_rows', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ingestionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='ingestion.tenant'),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(help_text='User who performed the action (hardcoded to analyst@demo.com in prototype)', max_length=255)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], max_length=10)),
                ('previous_status', models.CharField(max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emission_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='ingestion.normalizedemissionrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
